---
- import_tasks: redhat.yml
  when: ansible_os_family|lower == 'redhat'
- name: Place icinga2.conf
  template:
    src: icinga2.conf.j2
    dest: /etc/icinga2/icinga2.conf
    owner: root
    group: root
    mode: 0644
  when: icinga_manage_config | bool
  notify:
    - Restart Icinga

