---
# tasks file for icinga
- group_by:
    key: os_{{ ansible_os_family|lower }}{{ ansible_distribution_major_version }}
  when: ansible_system|lower == 'linux' or ansible_system|lower == 'darwin'
- group_by:
    key: os_{{ ansible_os_family|lower }}{{ ansible_distribution_version }}
  when: ansible_system|lower == 'sunos'
- import_tasks: linux.yml
  when: ansible_system|lower == 'linux'
- import_tasks: master.yml
  when: "'icinga_master' in group_names"
- import_tasks: configmaster.yml
  when: "'icinga_configmaster' in group_names"
- name: Enable API feature
  command: icinga2 feature enable api
  args:
    creates: /etc/icinga2/features-enabled/api.conf
  when: icinga_manage_config | bool
  notify:
    - Restart Icinga
- import_tasks: icingaweb.yml
  when: "'icinga_master' in group_names"
