---
- name: Install MySQL IDO package
  package:
    name: icinga2-ido-mysql
  notify:
    - Import IDO MySQL schema
- name: Configure IDO connection
  template:
    src: ido-mysql.conf.j2
    dest: /etc/icinga2/features-available/ido-mysql.conf
    owner: root
    group: icinga
    mode: 0640
  notify:
    - Restart Icinga
- name: Enable IDO feature
  command: icinga2 feature enable ido-mysql
  args:
    creates: /etc/icinga2/features-enabled/ido-mysql.conf
  notify:
    - Restart Icinga
