---
# handlers file for icinga
- name: Restart Icinga
  service:
    name: icinga2
    state: restarted
- name: Reload Icinga
  service:
    name: icinga2
    state: reloaded
- name: Import IDO MySQL schema
  mysql_db:
    name: icinga
    state: import
    target: /usr/share/icinga2-ido-mysql/schema/mysql.sql
